data:
  data_location: D:/Music/Datasets/nsynth-train-flute
  # data_location: /slow-2/georges/dataset-urmp-wav
  extension: "wav"

preprocess:
  sampling_rate: &samplingrate 16000
  signal_length: &signallength 64000
  block_size: &blocksize 256 # must be a power of 2 if using realtime

  oneshot: false # crop every audio file to exactly signal length
  out_dir: ./datasets/nsynth-train-flute/preprocessed

model:
  hidden_size: 512
  n_harmonic: 100
  n_bands: 65
  sampling_rate: *samplingrate
  block_size: *blocksize

train:
  scales: [4096, 2048, 1024, 512, 256, 128]
  overlap: .75

validation:
  data_dir: ./datasets/nsynth-valid-flute/preprocessed

test:
  pretrained_model_location: ./export/ddsp_mytraining_pretrained.ts
  data_dir: ./datasets/nsynth-test-flute/preprocessed